import datetime
from pathlib import Path

# Import modules from the project
from iterative_topic_expansion import IterativeTopicExpansion
from data_collection_module import DataCollection
from preprocessing_module import Preprocessing
from embeddings_training_automl import SequentialEmbeddingTrainingAutoML, ModelType
from dotproduct_generation_module import ValidationModule
# from selection_module import ModelSelector # To be created
from latent_knowledge_report_module import LatentKnowledgeReportGenerator
from utils import LoggerFactory

def run_full_pipeline(disease_name: str, max_topics: int, max_new_topics: int):
    """
    Orchestrates the full pipeline as described in pseudocode.txt.
    """
    logger = LoggerFactory.setup_logger("MainPipeline", log_to_file=True, log_file='main_pipeline.log')
    logger.info(f"Starting full pipeline for disease: {disease_name}")

    # ===================================================================================
    # PHASE 1: Iterative Topic Expansion (string_definition)
    # ===================================================================================
    logger.info("="*80)
    logger.info("PHASE 1: Iterative Topic Expansion")
    logger.info("="*80)

    topic_expander = IterativeTopicExpansion(
        disease_name=disease_name,
        max_topics=max_topics,
        max_new_topics=max_new_topics
    )
    last_expansion_year = topic_expander.run()
    logger.info(f"Topic expansion phase concluded. The last processed year was {last_expansion_year}.")

    # ===================================================================================
    # PHASE 2: Models Development
    # ===================================================================================
    logger.info("="*80)
    logger.info("PHASE 2: Models Development")
    logger.info("="*80)

    model_dev_start_year = last_expansion_year + 1
    today_year = datetime.datetime.now().year
    logger.info(f"Model development phase will run from {model_dev_start_year} to {today_year}.")

    # 2.1: Full Data Collection for the new period
    logger.info("Running full data collection for the model development period...")
    for year in range(model_dev_start_year, today_year + 1):
        logger.info(f"Collecting data for year {year}...")
        dc = DataCollection(disease_name=disease_name, target_year=year)
        dc.run()
    logger.info("Full data collection complete.")

    # 2.2: Full Preprocessing for the new period
    # NOTE: The current Preprocessing module in full mode processes all available files.
    # To prevent data leakage from the topic expansion phase, a modification would be
    # needed to allow `clean_and_normalize` to process only a specific range of years.
    # For now, we assume this is handled and run it in full mode.
    logger.info("Running full preprocessing for the model development period...")
    preprocessor = Preprocessing(disease_name=disease_name, target_year=today_year, incremental=False)
    preprocessor.run(force_full=True)
    logger.info("Full preprocessing complete.")

    # 2.3: AutoML Model Training
    logger.info("Starting AutoML training for all candidate models...")
    embedding_trainer = SequentialEmbeddingTrainingAutoML(
        disease_name=disease_name,
        start_year=model_dev_start_year,
        end_year=today_year,
        automl_config={
            'candidate_models': [
                ModelType.WORD2VEC,
                ModelType.FASTTEXT,
                ModelType.GLOVE,
            ],
            'use_pca_variants': True,
            'model_selection_time_budget': 1800, # 30 mins per model family
            'hyperopt_trials': 5,
            'hyperopt_timeout': 900, # 15 mins per trial
        },
    )
    embedding_trainer.run_automl()
    logger.info("AutoML training complete.")

    # 2.4: Validation of all generated models
    logger.info("Running validation for all models generated by AutoML...")
    validator = ValidationModule(
        disease_name=disease_name,
        start_year=model_dev_start_year,
        end_year=today_year
    )
    validator.run()
    logger.info("Validation complete for all models.")


    # ===================================================================================
    # PHASE 3: Selection
    # ===================================================================================
    logger.info("="*80)
    logger.info("PHASE 3: Model Selection")
    logger.info("="*80)

    # --- TO BE IMPLEMENTED ---
    # This phase requires a new module, e.g., 'selection_module.py'.
    #
    # logger.info("Selecting the best model based on latent knowledge metrics...")
    #
    # selector = ModelSelector(
    #     disease_name=disease_name,
    #     start_year=model_dev_start_year,
    #     end_year=today_year
    # )
    #
    # # This method would analyze all the compound_history files generated for
    # # each model and calculate a score based on "antecedence" - how early a
    # # model discovered a compound that later became relevant.
    # best_model_name = selector.select_best_model()
    #
    # logger.info(f"Best model selected: {best_model_name}")
    #
    # For now, we will hardcode a winner to allow the pipeline to be structured.
    best_model_name = "word2vec" # Placeholder
    logger.warning(f"Model selection is not yet implemented. Using placeholder: '{best_model_name}'")


    # ===================================================================================
    # PHASE 4: Final Test / Report
    # ===================================================================================
    logger.info("="*80)
    logger.info("PHASE 4: Final Report Generation")
    logger.info("="*80)

    # --- TO BE IMPLEMENTED (using the result from Phase 3) ---
    # This phase uses the best model selected in Phase 3 to generate a final report.

    logger.info(f"Generating final report using the selected model: '{best_model_name}'...")
    #
    # final_reporter = LatentKnowledgeReportGenerator(
    #     disease_name=disease_name,
    #     model_type=best_model_name,
    #     target_year=today_year,
    # )
    # final_reporter.run(generate_latex=True)
    #
    logger.info("Final report generation complete.")


    logger.info("="*80)
    logger.info("FULL PIPELINE FINISHED")
    logger.info("="*80)


if __name__ == '__main__':
    run_full_pipeline(
        disease_name='acute myeloid leukemia',
        max_topics=15, # Using a small number for testing purposes
        max_new_topics=8
    )
